apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    name: dbclean
  name: dbclean
  namespace: gitlab-postgres
spec:
  backoffLimit: 1
  completions: 1
  minReadySeconds: {}
  parallelism: 1
  template:
    metadata:
      annotations: {}
      labels:
        name: dbclean
    spec:
      affinity: {}
      containers:
        - args: {}
          command: {}
          image: example.com/postgres:14.5-alpine
          imagePullPolicy: IfNotPresent
          livenessProbe: {}
          name: dbclean
          readinessProbe: {}
          resources: {}
          securityContext: {}
          startupProbe: {}
          volumeMounts:
            - mountPath: /tmp/script.sql
              name: dbscript
              readOnly: null
              subPath: script.sql
      dnsPolicy: {}
      initContainers: []
      restartPolicy: Never
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 360
            items: []
            name: dbclean-4468eec4
          name: dbscript
  volumeClaimTemplates: []
