parameters:
  target_name: ${_reclass_:name:short}
  docs:
    - templates/docs/my_readme.md
  kapitan:
    vars:
      target: ${target_name}
    compile:
      - output_path: .
        input_type: jinja2
        input_paths: ${docs}
      - output_path: manifests
        input_type: kadet
        output_type: yml
        input_paths:
          - components/kubernetes
  generators:
    manifest:
      default_config:
        type: job
        service_account:
          create: false
        annotations:
          "manifests.kapicorp.com/generated": "true"
