parameters:
  target_name: ${_reclass_:name:short}
  kapitan:
    vars:
      target: ${target_name}
    compile:
      - output_path: .
        input_type: jinja2
        input_paths: ${docs}
  docs:
    - templates/docs/my_readme.md
