classes:
  - common
  - gitlab.helm

parameters:
  fqdn: stg.example.com
  charts:
    gitlab:
      helm_values:
        global:
          hosts:
            gitlab:
              name: gitlab.${fqdn}
