classes:
  - common
  - gitlab.helm

parameters:
  charts:
    gitlab:
      fqdn: stg.myvpc.${domain}
      instance_name: ${charts:gitlab:name}.${charts:gitlab:fqdn}
    minio:
      fqdn: console.stg.myvpc
