classes:
  - .config

parameters:
  kapitan:
    dependencies:
      - type: helm
        output_path: ${charts:gitlab:chart_path}
        source: ${charts:gitlab:repo}
        version: ${charts:gitlab:version}
        chart_name: ${charts:gitlab:name}
    compile:
      - input_type: helm
        output_path: ${charts:gitlab:name}
        input_paths:
          - ${charts:gitlab:chart_path}
        helm_values: ${charts:gitlab:helm_values}
        helm_params:
          namespace: ${charts:gitlab:namespace}
          name: ${charts:gitlab:name}
      - output_path: ${charts:gitlab:name}
        input_type: jinja2
        input_paths:
          - templates/docs/gitlab-values.yaml
          - templates/scripts/deploy.sh
