parameters:
  charts:
    gitlab:
      helm_values: 
        global:
          hosts:
            domain: ${fqdn}
            gitlab:
              name: gitlab.${fqdn}
          pages:
            host: pages.${fqdn}
