parameters:
  domain: in.example.com
  charts:
    minio:
      name: minio
      namespace: gitlab-object-storage
      version: 12.1.3
      chart_path: charts/minio/${charts:minio:version}
      helm_values:
        global:
          imageRegistry: proxy.example.com
        auth:
          existingSecret: root-console-user
        mode: distributed
        statefulset:
          replicaCount: 8
          zones: 2
          drivesPerNode: 2
        persistence:
          enabled: true
          size: 32Gi
        provisioning:
          enabled: true
          buckets:
            - name: registry
            - name: git-lfs
            - name: runner-cache
            - name: gitlab-uploads
            - name: gitlab-artifacts
            - name: gitlab-backups
            - name: gitlab-packages
            - name: tmp
            - name: gitlab-mr-diffs
            - name: gitlab-terraform-state
            - name: gitlab-ci-secure-files
            - name: gitlab-dependency-proxy
            - name: gitlab-pages
          usersExistingSecrets:
            - centralized-minio-users
        extraEnvVars:
          - name: MINIO_PROMETHEUS_URL
            value: http://prometheus.kube-system.svc:9090
          - name: MINIO_PROMETHEUS_JOB_ID
            value: minio
        ingress:
          enabled: true
          ingressClassName: internal-nginx
          hostname: ${charts:minio:fqdn}.${domain}
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production-issuer
          path: /
          tls: true
        metrics:
          serviceMonitor:
            enabled: true
            labels:
              release: kube-prometheus-stack
        podAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/path: "/minio/v2/metrics/cluster"
          prometheus.io/port: "9000"
          release: kube-prometheus-stack
        serviceAccount:
          name: minio-sa
